name: Auto Send Microsoft Teams Message

on:
  repository_dispatch:
    types: [run-teams-bot]
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          TEAMS_EMAIL: ${{ secrets.TEAMS_EMAIL }}
          TEAMS_PASSWORD: ${{ secrets.TEAMS_PASSWORD }}
        run: python team_bot.py
