name: Auto Send Microsoft Teams Message

on:
  schedule:
    - cron: '49 1 * * *'  # 09:45 VN time (UTC+7)
    - cron: '43 7 * * *'  # 15:15 VN time (UTC+7)
  workflow_dispatch:       # Cho phép chạy thủ công

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python team_bot.py
